# ===================================================
# meta infos
# ===================================================
meta:
  project: alm-service-modules
  include:
    - dobi.yaml
    - version.yaml
    - alm-location-module/dobi.yaml
    - alm-mqtt-module/dobi.yaml
    - gpsfake-module/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-alm-location-module
    - build-and-push-image-alm-location-module
    - build-alm-mqtt-module
    - build-and-push-image-alm-mqtt-module
    - build-and-push-image-gpsfake-module
  annotations:
    description: "[alias] build (and push) all"
    tags:
      - alias
