---
# Project configuration
# -----------------------------
## Defines the name for the project
name: alm-service-modules

# Git configuration
# -----------------
## Specify the git repository to work with
git_source: https://github.com/edgefarm/alm-service-modules.git
## Specify the git branch to work with
git_branch: main
## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false
